UrIU/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("backend.urls")),
]

backend/forms.py
from django import forms
from .models import Contact

class QabulForm(forms.Form):
    full_name = forms.CharField(label="To'liq ismi", max_length=255)
    passport = forms.CharField(label='Passport seriyasi', max_length=20)
    viloyat = forms.CharField(label='Viloyat', max_length=255)
    tuman = forms.CharField(label='Tuman', max_length=255)
    mfy = forms.CharField(label='MFY', max_length=255)
    kucha = forms.CharField(label='Kucha', max_length=255)
    uy = forms.CharField(label='Uy', max_length=255)
    phone_number = forms.CharField(label='Telefon raqami', max_length=15)
    
    birthday = forms.DateField(label="Tug'gilgan kuni", widget=forms.DateInput(attrs={'type': 'date'}))
    school = forms.CharField(label='Tugatgan ta’lim muassasasi', max_length=255)
    attestat = forms.CharField(label="Diplom yoki attestat raqami: № ", max_length=255)
    languages = forms.CharField(label="Qaysi chet til(lar)ini o‘qigan", max_length=255)
    father = forms.CharField(label="Otasi", max_length=255)
    father_address = forms.CharField(label="Doimiy yashash manzili", max_length=255)
    father_job = forms.CharField(label="Doimiy ish joyi", max_length=255)
    father_phone_number = forms.CharField(label="Telefon raqami", max_length=15)
    
    mother = forms.CharField(label="Onasi", max_length=255)
    mother_address = forms.CharField(label="Doimiy yashash manzili", max_length=255)
    mother_job = forms.CharField(label="Doimiy ish joyi", max_length=255)
    mother_phone_number = forms.CharField(label="Telefon raqami", max_length=15)
    directions = forms.ChoiceField(
        label="Yo'nalish", 
        choices=[
        ("Boshlang'ich ta'lim", "Boshlang'ich ta'lim"),
        ("Tarix", "Tarix"),
        ("Filoligiya va tillarni o'qitish(O'zbek tili)", "Filoligiya va tillarni o'qitish(O'zbek tili)"),
        ("Filoligiya va tillarni o'qitish(Ingliz tili)", "Filoligiya va tillarni o'qitish(Ingliz tili)"),
        ],
    )
    education_type = forms.ChoiceField(
        label="Ta'lim shakli",
        choices=[
            ('Kunduzgi', 'Kunduzgi'),
            ('Sirtqi', 'Sirtqi'),
        ]
    )


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'phone', 'directions', 'education_type']

templates/qabul/document.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<h2>{{ qabul.phone }}</h2>
<section class="section icon-list section-lg bg-default">
    <div class="container">
        <div class="col-md-4 col-lg-3 col-sm-6" href="/media/contract/{{qabul.passport}}.docx" >
            <div class="unit unit-spacing-xsm flex-row align-items-center">
                <div class="unit-left"><span class="icon icon-madison mdi mdi-file-document"></span></div>
                <div class="unit-body">
                    <p><a href="/media/contract/{{qabul.passport}}.docx">Shartnoma</a></p>
                </div>
            </div>
            <div class="unit unit-spacing-xsm flex-row align-items-center">
                <div class="unit-left"><span class="icon icon-madison mdi mdi-file-document"></span></div>
                <div class="unit-body">
                    <p><a href="/media/application/{{qabul.passport}}.docx">Ariza</a></p>
                </div>
            </div>
        </div>
    </div>
</section>
{% include "./footer.html" %}
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/qabul/error.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<h2>Error</h2>

{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/qabul/qabul.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<div class="containerr">
    <h2>Ma'lumotlarni kiriting</h2>
    <form method="post">
        {% csrf_token %}
        <div class="row align-items-center">
            <div class="col-6"><label for="id_full_name">To'liq ismi:</label></div>
            <div class="col-6 text-start">{{ form.full_name }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_passport">Passport seriyasi:</label></div>
            <div class="col-6 text-start">{{ form.passport }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_viloyat">Viloyat:</label></div>
            <div class="col-6 text-start">{{ form.viloyat }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_tuman">Tuman:</label></div>
            <div class="col-6 text-start">{{ form.tuman }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mfy">MFY:</label></div>
            <div class="col-6 text-start">{{ form.mfy }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_kucha">Kucha:</label></div>
            <div class="col-6 text-start">{{ form.kucha }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_uy">Uy:</label></div>
            <div class="col-6 text-start">{{ form.uy }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_phone_number">Telefon raqami:</label></div>
            <div class="col-6 text-start">{{ form.phone_number }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_birthday">Tug'gilgan kuni:</label></div>
            <div class="col-6 text-start">{{ form.birthday }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_school">Tugatgan ta’lim muassasasi:</label></div>
            <div class="col-6 text-start">{{ form.school }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_attestat">Diplom yoki attestat raqami:</label></div>
            <div class="col-6 text-start">{{ form.attestat }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_languages">Qaysi chet til(lar)ini o‘qigan:</label></div>
            <div class="col-6 text-start">{{ form.languages }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father">Otasi:</label></div>
            <div class="col-6 text-start">{{ form.father }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father_address">Doimiy yashash manzili:</label></div>
            <div class="col-6 text-start">{{ form.father_address }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father_job">Doimiy ish joyi:</label></div>
            <div class="col-6 text-start">{{ form.father_job }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father_phone_number">Telefon raqami:</label></div>
            <div class="col-6 text-start">{{ form.father_phone_number }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother">Onasi:</label></div>
            <div class="col-6 text-start">{{ form.mother }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother_address">Doimiy yashash manzili:</label></div>
            <div class="col-6 text-start">{{ form.mother_address }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother_job">Doimiy ish joyi:</label></div>
            <div class="col-6 text-start">{{ form.mother_job }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother_phone_number">Telefon raqami:</label></div>
            <div class="col-6 text-start">{{ form.mother_phone_number }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_directions">Yo'nalish:</label></div>
            <div class="col-6 text-start">{{ form.directions }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_education_type">Ta'lim shakli:</label></div>
            <div class="col-6 text-start">{{ form.education_type }}</div>
        </div>
        <br>
        <button type="submit">Jo'natish</button>
    </form>
</div>

{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/qabul/success.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<h2>Success</h2>

{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}