UrIU/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("backend.urls")),
]

backend/models.py
# backend/models.py

from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models

class Contact(models.Model):
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15, unique=True, verbose_name='Телефон')
    directions = models.CharField(max_length=255, choices=[
        ("Boshlang'ich ta'lim", "Boshlang'ich ta'lim"),
        ("Tarix", "Tarix"),
        ("Filoligiya va tillarni o'qitish(O'zbek tili)", "Filoligiya va tillarni o'qitish(O'zbek tili)"),
        ("Filoligiya va tillarni o'qitish(Ingliz tili)", "Filoligiya va tillarni o'qitish(Ingliz tili)"),
        ],
        default="Boshlangich ta'lim"
    )
    education_type = models.CharField(max_length=20, choices=[
        ('full_time', 'Kunduzgi'),
        ('part_time', 'Sirtqi'),
        ],
        default='part_time'
    )
    status = models.BooleanField(default=False, verbose_name='Статус')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'

    def __str__(self):
        return self.full_name

class Qabul(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    passport = models.CharField(max_length=20, unique=True)
    viloyat = models.CharField(max_length=255)
    tuman = models.CharField(max_length=255)
    mfy = models.CharField(max_length=255)
    kucha = models.CharField(max_length=255)
    uy = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15)
    birthday = models.DateField(null=True, blank=True)
    school = models.CharField(max_length=255)
    attestat = models.CharField(max_length=255)
    languages = models.CharField(max_length=255)
    father = models.CharField(max_length=255)
    father_address = models.CharField(max_length=255)
    father_job = models.CharField(max_length=255)
    father_phone_number = models.CharField(max_length=15)
    
    mother = models.CharField(max_length=255)
    mother_address = models.CharField(max_length=255)
    mother_job = models.CharField(max_length=255)
    mother_phone_number = models.CharField(max_length=15)
    directions = models.CharField(max_length=255, choices=[
        ("Boshlang'ich ta'lim", "Boshlang'ich ta'lim"),
        ("Tarix", "Tarix"),
        ("Filoligiya va tillarni o'qitish(O'zbek tili)", "Filoligiya va tillarni o'qitish(O'zbek tili)"),
        ("Filoligiya va tillarni o'qitish(Ingliz tili)", "Filoligiya va tillarni o'qitish(Ingliz tili)"),
        ],
        default="Boshlangich ta'lim"
    )
    education_type = models.CharField(max_length=20, choices=[
        ('full_time', 'Очное'),
        ('part_time', 'Заочное'),
    ])
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def address(self):
        return f'{self.viloyat}, {self.tuman}, {self.kucha}, uy-{self.uy}'
        
    class Meta:
        verbose_name = 'приём'
        verbose_name_plural = 'приём'

    def __str__(self):
        return self.full_name


class FileForDocuments(models.Model):
    name = models.CharField(max_length=255, verbose_name='Названия')
    document = models.ForeignKey('Document', related_name='Document', on_delete=models.CASCADE)
    file = models.FileField(upload_to='documents/')
    
    def __str__(self):
        return f"File {self.pk}"

class Document(models.Model):
    title_uz = models.CharField(max_length=255, verbose_name='*Заголовка(uz)')
    title_en = models.CharField(max_length=255, verbose_name='*Заголовка(en)')
    title_ru = models.CharField(max_length=255, verbose_name='*Заголовка(ru)')

    body_uz = RichTextField(max_length=255, verbose_name='Текст(uz)')
    body_en = RichTextField(max_length=255, verbose_name='Текст(en)')
    body_ru = RichTextField(max_length=255, verbose_name='Текст(ru)')

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'
    
    def __str__(self):
        return self.title_uz
    

class SertificateForEmployee(models.Model):
    queue = models.IntegerField(default=1, verbose_name='Очеред показа(Необязательно)')
    employee = models.ForeignKey('Employee', related_name='SertificateForEmployee', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='sertificates/')

    def __str__(self):
        return f"Image {self.pk}"

class Employee(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to='employee_photos/')

    full_name_uz = models.CharField(max_length=255, verbose_name='*ФИО(uz)')
    full_name_en = models.CharField(max_length=255, verbose_name='*ФИО(en)')
    full_name_ru = models.CharField(max_length=255, verbose_name='*ФИО(ru)')

    proffesion_uz = models.CharField(max_length=255, verbose_name='*Профессия(uz)')
    proffesion_en = models.CharField(max_length=255, verbose_name='*Профессия(en)')
    proffesion_ru = models.CharField(max_length=255, verbose_name='*Профессия(ru)')

    about_uz = RichTextField(verbose_name='*Инфо(uz)')
    about_en = RichTextField(verbose_name='*Инфо(en)')
    about_ru = RichTextField(verbose_name='*Инфо(ru)')

    phone = models.CharField(max_length=20, null=True, blank=True, verbose_name='Телефон')
    email = models.CharField(max_length=255, null=True, blank=True, verbose_name='Почта')

    telegram = models.URLField(max_length=200, blank=True, null=True, verbose_name='Телеграм(https://t.me/username)')
    facebook = models.URLField(max_length=200, blank=True, null=True, verbose_name='Facebook(link)')
    instagram = models.URLField(max_length=200, blank=True, null=True, verbose_name='Инстаграм(link)')


    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
    
    def __str__(self):
        return self.full_name_uz



class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'заголовка'
        verbose_name_plural = 'заголовки'

    def __str__(self):
        return self.name

class Button(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    link = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'кнопка'
        verbose_name_plural = 'кнопки'

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'
    def __str__(self):
        return self.name

class GalleryForNews(models.Model):
    news = models.ForeignKey('News', related_name='gallery_for_news', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='news_gallery/')

    def __str__(self):
        return f"Image {self.pk}"

class News(models.Model):
    title_uz = models.CharField(max_length=200)
    title_ru = models.CharField(max_length=200)
    title_en = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='news_photos/')
    you_tube_video_link = models.URLField(max_length=255, blank=True, null=True)
    text_uz = RichTextField()
    text_en = RichTextField()
    text_ru = RichTextField()
    tags = models.ManyToManyField(Tag)
    date = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'

    def __str__(self):
        return self.title_uz

class Template(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Ключь')
    body_en = models.TextField(verbose_name='English')
    body_ru = models.TextField(verbose_name='Русский')
    body_uz = models.TextField(verbose_name='Uzbekcha')

    class Meta:
        verbose_name = 'Шаблон'
        verbose_name_plural = 'Шаблоны'

    def __str__(self):
        return self.title

class Template2Button(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Ключь')
    body_en = models.TextField(verbose_name='English')
    body_ru = models.TextField(verbose_name='Русский')
    body_uz = models.TextField(verbose_name='Uzbekcha')

    class Meta:
        verbose_name = 'Небольшой шаблон'
        verbose_name_plural = 'Небольшие шаблоны'

    def __str__(self):
        return self.title

class Gallery(models.Model):
    photo = models.ImageField(upload_to='gallery_photos/')
    description_en = models.TextField(null=True, blank=True, verbose_name='English')
    description_ru = models.TextField(null=True, blank=True, verbose_name='Русский')
    description_uz = models.TextField(null=True, blank=True, verbose_name='Uzbekcha')
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галерея'

    def __str__(self):
        return f'Gallery #{self.id}'

class Quote(models.Model):
    photo = models.ImageField(upload_to='gallery_photos/')

    name_uz = models.CharField(max_length=255)
    name_ru = models.CharField(max_length=255)
    name_en = models.CharField(max_length=255)

    short_text_uz = models.CharField(max_length=255)
    short_text_ru = models.CharField(max_length=255)
    short_text_en = models.CharField(max_length=255)

    text_uz = models.TextField()
    text_ru = models.TextField()
    text_en = models.TextField()

    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'цитата'
        verbose_name_plural = 'цитаты'
    
    def __str__(self):
        return self.name_uz

templates/frontend/RTT.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Raqamli ta'lim texnologiyalar bo'limi" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<section class="section section-xl bg-default">
    <div class="container">
      <h2 class="fw-bold">{% call_get_text "Raqamli ta'lim texnologiyalar bo'limi" language True%}</h2>
      <hr class="divider bg-madison">
      <h5>{% call_get_text "RTT INFO" language False%}</h5>
      <div class="row row-30 text-lg-start offset-top-60">
        {% for employee in employees %}
          <div class="col-md-6 col-lg-3">
              <a href="/{{language}}/employee-{{employee.id}}">
                  <img class="img-responsive d-inline-block img-rounded" src="{{employee.photo.url}}" style="width:270px; height:270px;" alt="">
                  <div class="offset-top-20">
                      <h6 class="fw-bold text-primary">
                        {% if language == 'en' %}
                            {{ employee.full_name_en }}
                        {% elif language == 'ru' %}
                          {{ employee.full_name_ru }}
                        {% else %}
                          {{ employee.full_name_uz }}
                        {% endif %}
                      </h6>
                  </div>
                  <div class="offset-top-5">
                      <p>
                        {% if language == 'en' %}
                            {{ employee.proffesion_en }}
                        {% elif language == 'ru' %}
                          {{ employee.proffesion_ru }}
                        {% else %}
                          {{ employee.proffesion_uz }}
                        {% endif %}</p>
                  </div>
              </a>
          </div>
        {% endfor %}
        
      </div>
    </div>
  </section>
{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/frontend/coming_soon.html
{% load static %}
{% load my_tags %}
<section class="section section-cover section-404 section-30 bg-default container">
  <div class="section-50">
    <div class="offset-top-10">
      <h2 class="fw-bold">{% call_get_text "coming soon" language True%}</h2>
    </div>
    <div class="offset-top-15 offset-lg-top-30">
      <hr class="divider bg-madison">
    </div>
    <div class="offset-top-30 offset-lg-top-60" style="max-width: 800px; margin-left: auto; margin-right: auto">
      <div class="countdown" data-countdown="data-countdown" data-to="2024-05-01">
        <div class="countdown-block countdown-block-days">
          <div class="countdown-wrapper">
            <svg class="countdown-circle" x="0" y="0" width="200" height="200" viewbox="0 0 200 200" data-progress-days="">
              <circle class="countdown-circle-bg" cx="100" cy="100" r="90"></circle>
              <circle class="countdown-circle-fg clipped" cx="100" cy="100" r="90"></circle>
            </svg>
            <div class="countdown-counter" data-counter-days="">00</div>
          </div>
          <div class="countdown-title">{% call_get_text "kun" language True%}</div>
        </div>
        <div class="countdown-block countdown-block-hours">
          <div class="countdown-wrapper">
            <svg class="countdown-circle" x="0" y="0" width="200" height="200" viewbox="0 0 200 200" data-progress-hours="">
              <circle class="countdown-circle-bg" cx="100" cy="100" r="90"></circle>
              <circle class="countdown-circle-fg clipped" cx="100" cy="100" r="90"></circle>
            </svg>
            <div class="countdown-counter" data-counter-hours="">00</div>
          </div>
          <div class="countdown-title">{% call_get_text "soat" language True%}</div>
        </div>
        <div class="countdown-block countdown-block-minutes">
          <div class="countdown-wrapper">
            <svg class="countdown-circle" x="0" y="0" width="200" height="200" viewbox="0 0 200 200" data-progress-minutes="">
              <circle class="countdown-circle-bg" cx="100" cy="100" r="90"></circle>
              <circle class="countdown-circle-fg clipped" cx="100" cy="100" r="90"></circle>
            </svg>
            <div class="countdown-counter" data-counter-minutes="">00</div>
          </div>
          <div class="countdown-title">{% call_get_text "daqiqa" language True%}</div>
        </div>
        <div class="countdown-block countdown-block-seconds">
          <div class="countdown-wrapper">
            <svg class="countdown-circle" x="0" y="0" width="200" height="200" viewbox="0 0 200 200" data-progress-seconds="">
              <circle class="countdown-circle-bg" cx="100" cy="100" r="90"></circle>
              <circle class="countdown-circle-fg clipped" cx="100" cy="100" r="90"></circle>
            </svg>
            <div class="countdown-counter" data-counter-seconds="">00</div>
          </div>
          <div class="countdown-title">{% call_get_text "soniya" language True%}</div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/frontend/contact.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "contact" language True%}{% endblock %}

{% block body %}
      {% include "./header.html" %}
      <section class="section mt-3 mb-5 bg-default">
        <div class="container">
          <div class="row row-50 justify-content-sm-center">
            <div class="col-sm-10 col-lg-8 text-lg-start">
              <h2 class="fw-bold">{% call_get_text "Get in Touch" language True%}</h2>
              <hr class="divider bg-madison divider-lg-0">
              <div class="offset-top-30 offset-md-top-60">
                <p>You can contact us any way that is convenient for you. We are available 24/7 via fax or email. You can also use a quick contact form below or visit our office personally. We would be happy to answer your questions.</p>
              </div>
              <div class="offset-top-30">
                <form class="rd-mailform text-start" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
                  <div class="row row-12">
                    <div class="col-xl-6">
                      <div class="form-wrap">
                        <label class="form-label form-label-outside" for="contact-me-name">First name</label>
                        <input class="form-input" id="contact-me-name" type="text" name="name" data-constraints="@Required">
                      </div>
                    </div>
                    <div class="col-xl-6">
                      <div class="form-wrap">
                        <label class="form-label form-label-outside" for="contact-me-last-name">Last name</label>
                        <input class="form-input" id="contact-me-last-name" type="text" name="last-name" data-constraints="@Required">
                      </div>
                    </div>
                    <div class="col-xl-6">
                      <div class="form-wrap">
                        <label class="form-label form-label-outside" for="contact-me-email">E-mail</label>
                        <input class="form-input" id="contact-me-email" type="email" name="email" data-constraints="@Required @Email">
                      </div>
                    </div>
                    <div class="col-xl-6">
                      <div class="form-wrap">
                        <label class="form-label form-label-outside" for="contact-me-phone">Phone</label>
                        <input class="form-input" id="contact-me-phone" type="text" name="phone" data-constraints="@Required @IsNumeric">
                      </div>
                    </div>
                    <div class="col-xl-12">
                      <div class="form-wrap">
                        <label class="form-label form-label-outside" for="contact-me-message">Message</label>
                        <textarea class="form-input" id="contact-me-message" name="message" data-constraints="@Required" style="height: 220px"></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="text-center text-xl-start offset-top-20">
                    <button class="btn button-primary" type="submit">Send Message</button>
                  </div>
                </form>
              </div>
            </div>
            <div class="col-sm-10 col-lg-4 text-start">
              <div class="inset-lg-left-30">
                <h6 class="fw-bold">{% call_get_text "Socials" language True%}</h6>
                <div class="hr bg-gray-light offset-top-10"></div>
                <div class="offset-top-15 text-start">
                  <ul class="list-inline list-inline-xs list-inline-madison">
                    <li><a class="icon icon-xxs fa fa-facebook icon-circle icon-gray-light-filled" href="https://www.facebook.com/profile.php?id=100091826560046"></a></li>
                    <li><a class="icon icon-xxs fa fa-youtube icon-circle icon-gray-light-filled" href="https://www.youtube.com/@uriu/about"></a></li>
                    <li><a class="icon icon-xxs fa fa-telegram icon-circle icon-gray-light-filled" href="https://t.me/urganch_iu"></a></li>
                    <li><a class="icon icon-xxs fa fa-instagram icon-circle icon-gray-light-filled" href="http://instagram.com/urganch_innovatsion_university"></a></li>
                  </ul>
                </div>
                <div class="offset-top-30 offset-md-top-60">
                  <h6 class="fw-bold">{% call_get_text "Phones" language True%}</h6>
                  <div>
                    <div class="hr bg-gray-light offset-top-10"></div>
                  </div>
                  <div class="offset-top-15">
                    <ul class="list list-unstyled">
                       
                      <li><span class="icon icon-xs text-madison mdi mdi-phone align-middle"></span><a class="text-dark" href="tel:+998904362022">90 436-20-22</a></li>
                      <li><span class="icon icon-xs text-madison mdi mdi-phone align-middle"></span><a class="d-block d-lg-inline-block text-dark" href="tel:+998914362022">91 436-20-22</a></li>
                    </ul>
                  </div>
                </div>
                <div class="offset-top-30 offset-md-top-60">
                  <h6 class="fw-bold">{% call_get_text "email" language True%}</h6>
                  <div>
                    <div class="hr bg-gray-light offset-top-10"></div>
                  </div>
                  <div class="offset-top-15">
                    <ul class="list list-unstyled">
                      <li><span class="icon icon-xs text-madison mdi mdi-email-outline align-middle"></span><a class="align-middle inset-left-10" href="mailto:info@demolink.org">info@uriu.uz</a></li>
                    </ul>
                  </div>
                </div>
                <div class="offset-top-30 offset-md-top-60">
                  <h6 class="fw-bold">{% call_get_text "Address" language True%}</h6>
                  <div>
                    <div class="hr bg-gray-light offset-top-10"></div>
                  </div>
                  <div class="offset-top-15">
                    <div class="unit flex-row unit-spacing-xs">
                      <div class="unit-left"><span class="icon icon-xs mdi mdi-map-marker text-madison"></span></div>
                      <div class="unit-body">
                        <div class="unit-body text-start"><a class="text-dark" href="https://www.google.com/maps?ll=41.570595,60.614984&z=14&t=m&hl=ru&gl=US&mapclient=embed&cid=4823893255036828626">{% call_get_text 'address' language True%}</a></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="offset-top-30 offset-md-top-65">
                  <h6 class="fw-bold">{% call_get_text "Opening Hours" language True%}</h6>
                  <div>
                    <div class="hr bg-gray-light offset-top-10"></div>
                  </div>
                  <div class="offset-top-15">
                    <div class="unit flex-row unit-spacing-xs">
                      <div class="unit-left"><span class="icon icon-xs mdi mdi-calendar-clock text-madison"></span></div>
                      <div class="unit-body">
                        <div>
                          <p>{% call_get_text "Mon-: 9:00am-6:00pm" language True%}</p>
                        </div>
                        <div>
                          <p>{% call_get_text "Sun-Sat: Closed" language True%}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {% include "./footer.html" %}
     

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/frontend/employee.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}
{% if language == 'en' %}
    {{ employee.full_name_en }}
{% elif language == 'ru' %}
  {{ employee.full_name_ru }}
{% else %}
  {{ employee.full_name_uz }}
{% endif %}
{% endblock %}

{% block body %}

{% include "./header.html" %}
<section class="section section-xl bg-default">
    <div class="container">
      <div class="row row-30 justify-content-sm-center">
        <div class="col-md-5 col-lg-4 text-md-start">
          <div class="inset-md-right-30"><img class="img-responsive d-inline-block " src="{{ employee.photo.url }}" width="340" height="340" alt="">
            <div class="offset-top-15 offset-sm-top-30">
              <ul class="list list-unstyled">
                <li><span class="icon icon-xs mdi mdi-phone align-middle text-madison"></span><a class="d-inline-block text-dark inset-left-10" href="tel:{{employee.phone}}">{{employee.phone}}</a></li>
                <li><span class="icon icon-xs mdi mdi-email-open align-middle text-madison"></span><a class="d-inline-block inset-left-10" href="mailto:{{employee.email}}">{{employee.email}}</a></li>
              </ul>
            </div>
            <div class="offset-top-15 offset-sm-top-30">
              <ul class="list-inline list-inline-xs list-inline-madison">
                
                <li><a class="icon icon-xxs fa fa-telegram icon-circle icon-gray-light-filled" href="{% if employee.telegram %}{{ employee.telegram }}{% else %}#{% endif %}"></a></li>
                <li><a class="icon icon-xxs fa fa-facebook icon-circle icon-gray-light-filled" href="{% if employee.facebook %}{{ employee.facebook }}{% else %}#{% endif %}"></a></li>
                <li><a class="icon icon-xxs fa fa-instagram icon-circle icon-gray-light-filled" href="{% if employee.instagram %}{{ employee.instagram }}{% else %}#{% endif %}"></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-7 col-lg-8 text-start">
          <div>
            <h2 class="fw-bold">
              {% if language == 'en' %}
                  {{ employee.full_name_en }}
              {% elif language == 'ru' %}
                {{ employee.full_name_ru }}
              {% else %}
                {{ employee.full_name_uz }}
              {% endif %}
            </h2>
          </div>
          <p class="offset-top-10">
            {% if language == 'en' %}
                {{ employee.proffesion_en }}
            {% elif language == 'ru' %}
              {{ employee.proffesion_ru }}
            {% else %}
              {{ employee.proffesion_uz }}
            {% endif %}
            
          </p>
          
          <div class="offset-top-30 offset-md-top-30">

            <div class="text-subline"></div>
          </div>
          <div class="offset-top-20">
            <p>
              {% if language == 'en' %}
                {{ employee.about_en|safe }}
            {% elif language == 'ru' %}
              {{ employee.about_ru|safe }}
            {% else %}
              {{ employee.about_uz|safe }}
            {% endif %}
            </p>
          </div>
          <div class="offset-top-30 offset-md-top-60">
            <h6 class="fw-bold">{% call_get_text "Certificates and Awards" language True%}</h6>
            <div class="text-subline"></div>
          </div>
          <div class="offset-top-15 offset-sm-top-30">
            <div class="group group-lg" data-lightgallery="group">
              {% for certificate in sert %}
                  <a class="d-inline-block" data-lightgallery="item" href="{{ certificate.image.url }}">
                      <img class="img-responsive d-inline-block" src="{{ certificate.image.url }}" width="144" height="90" alt="">
                  </a>
              {% endfor %}

                
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/frontend/fakultetlar.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Fakultetlar" language True%}{% endblock %}

{% block body %}

    
    
      {% include "./header.html" %}
      {% include "./coming_soon.html" %}
      {% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/frontend/kengashlar.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Kengashlar" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
{% include "./coming_soon.html" %}
{% include "./footer.html" %}


<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/frontend/markazlar_va_bolimlar.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Markazlar va bo'limlar" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<section class="section section-xl bg-catskill">
    <div class="container">
        <div class="row row-85 justify-content-sm-center">
            {% comment %} <div class="col-lg-4 text-start col-sm-8">
                <aside class="inset-lg-left-30">
                    <h6 class="fw-bold">{% call_get_text tuzilma.name language True%}</h6>
                    <div class="text-subline"></div>
                    <div class="offset-top-20">
                        <ul class="list list-marked list-marked-primary">
                            {% for button in tuzilma.button_set.all %}
                                <li><a href="/{{language}}/{{ button.link }}">{% call_get_text button.name language True%}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                </aside>
            </div> {% endcomment %}
            <div class="col-lg-8 row-30">
                <h2>{% call_get_text "Markazlar" language True%}</h2>
                <hr class="divider bg-madison">

                    
                </div>
                <div class="mb-3">
                    <div class="group group-xl">
                        <a class="btn btn-icon btn-icon-right button-default w-100" href="#">
                            <span class="icon fa fa-arrow-right"></span>
                            <span>Learn More</span>
                        </a>
                    </div>
                </div>

                <h2>{% call_get_text "Bo'limlar" language True%}</h2>
                <hr class="divider bg-madison">
                <div class="mb-3">
                    <div class="group group-xl">
                        <a class="btn btn-icon btn-icon-right button-default w-100" href="/{{language}}/markazlar_va_bolimlar/rtt">
                            <span class="icon fa fa-arrow-right"></span>
                            <span>{% call_get_text "Raqamli ta'lim texnologiyalar bo'limi" language True%}</span>
                        </a>
                    </div>
                </div>
                
            </div>
            
        </div>
    </div>
</section>


{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/frontend/rekvizitlar.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Rekvizitlar" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
{% include "./coming_soon.html" %}
{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}